#include "StrRes.h"
#include <iostream>
#include <vector>

void LoadGameStringResources(std::unordered_map<int, std::string>* stringTable) 
{
    std::vector<std::pair<int, std::string>> strs = {
        {ID_GAME_REGISTER,       "Register HoverRace"},
        {IDS_DISABLE,            "Disable"},
        {IDS_SHIFT,              "Shift"},
        {IDS_CTRL,               "Ctrl"},
        {IDS_UP,                 "Up"},
        {IDS_DOWN,               "Down"},
        {IDS_RIGHT,              "Right"},
        {IDS_LEFT,               "Left"},
        {IDS_INS,                "Ins"},
        {IDS_DEL,                "Del"},
        {IDS_ENTER,              "Enter"},
        {IDS_CAPS,               "CapsLock"},
        {IDS_TAB,                "Tab"},
        {IDS_JOY1BTN1,           "Joystick Btn1"},
        {IDS_JOY1BTN2,           "Joystick Btn2"},
        {IDS_JOY1BTN3,           "Joystick Btn3"},
        {IDS_JOY1BTN4,           "Joystick Btn4"},
        {IDS_JOY1TOP,            "Joystick Top"},
        {IDS_JOY1DOWN,           "Joystick Down"},
        {IDS_JOY1RIGHT,          "Joystick Right"},
        {IDS_JOY1LEFT,           "Joystick Left"},
        {IDS_JOY2BTN1,           "Joystick2 Btn1"},
        {IDS_JOY2BTN2,           "Joystick2 Btn2"},
        {IDS_JOY2BTN3,           "Joystick2 Btn3"},
        {IDS_JOY2BTN4,           "Joystick2 Btn4"},
        {IDS_JOY2TOP,            "Joystick2 Top"},
        {IDS_JOY2DOWN,           "Joystick2 Down"},
        {IDS_JOY2RIGHT,          "Joystick2 Right"},
        {IDS_JOY2LEFT,           "Joystick2 Left"},
        {IDS_SPACE,              "Space"},
        {IDS_KEY_A,              "A Key"},
        {IDS_KEY_B,              "B Key"},
        {IDS_KEY_C,              "C Key"},
        {IDS_KEY_D,              "D Key"},
        {IDS_KEY_E,              "E Key"},
        {IDS_KEY_F,              "F Key"},
        {IDS_KEY_G,              "G Key"},
        {IDS_KEY_H,              "H Key"},
        {IDS_KEY_I,              "I Key"},
        {IDS_KEY_J,              "J Key"},
        {IDS_KEY_K,              "K Key"},
        {IDS_KEY_L,              "L Key"},
        {IDS_KEY_M,              "M Key"},
        {IDS_KEY_N,              "N Key"},
        {IDS_KEY_O,              "O Key"},
        {IDS_KEY_P,              "P Key"},
        {IDS_KEY_Q,              "Q Key"},
        {IDS_KEY_R,              "R Key"},
        {IDS_KEY_S,              "S Key"},
        {IDS_KEY_T,              "T Key"},
        {IDS_KEY_U,              "U Key"},
        {IDS_KEY_V,              "V Key"},
        {IDS_KEY_W,              "W Key"},
        {IDS_KEY_X,              "X Key"},
        {IDS_KEY_Y,              "Y Key"},
        {IDS_KEY_Z,              "Z Key"},
        {IDS_DEFAULT_ALIAS,      "your name"},
        {IDS_ABORT_GAME,         "Abort current game?"},
        {IDS_GAME_NAME,          "HoverRace"},
        {IDS_HELP_REQ,           "To be able to display Hover Race Help\nyou must have a Word document viewer installed\non your system\n"},
        {IDS_ERROR,              "HoverRace Error"},
        {IDS_WWW_REQ,            "Unable to activate your WebBrowser. Please start your WebBrowser and go to:\n%s"},
        {IDS_CAPTION,            "HoverRace v1.01"},
        {IDS_REG_CAPTION,        "HoverRace v1.01 [REGISTERED VERSION]"},
        {IDS_DEMO_CAPTION,       "HoverRace v1.01 [DEMO MODE]"},
        {IDS_MODE_SWITCH_TRY,    "HoverRace will try to switch your screen to a 256 colors mode"},
        {IDS_CANT_SWITCH_MODE,   "HoverRace was unable to switch the video mode. You will need to play in full screen"},
        {IDS_BAD_MODE,           "Incompatible video mode. You will need to play in full screen"},
        {IDS_CAR_FOR_REG,        "You need to register to use this craft model"},
        {IDS_COLOR_INTENSITY,    "Colors intensity"},
        {IDS_KEYS_SETTING,       "Keys"},
        {IDS_PROP_SETTING,       "Properties setting"},
        {IDS_READ_NOTICE,        "Please take the time to read the notice"},
        {IDS_BAD_PASSWD,         "Wrong password"},
        {IDS_NOT_HR_KEY,         "Not an HoverRace Key"},
        {IDS_FILL_OWNER,         "Please fill the \"Owner\" field"},
        {IDS_PASSWD_LEN,         "Password must have at max 10 characters"},
        {IDS_KEY1_LEN,           "Registration Key part 1 must have 20 character long"},
        {IDS_KEY2_LEN,           "Registration Key part 2 must have 20 character long"},
        {IDS_BAD_KEY1,           "Registration Key part 1 is invalid"},
        {IDS_BAD_KEY2,           "Registration Key part 2 is invalid"},
        {IDS_BAD_USER,           "Owner name does not match with the key"},
        {IDS_BAD_ID,             "User ID does not match with the key"},
        {IDS_CLEAR_REGINFO,      "Are you sure that you want to clear current registration key info?"},
        {IDS_IMR_CONNECT,        "Connecting to the Internet Meeting Room..."},
        {IDS_UR_CONNECT,         "You are Connected"},
        {IDS_IMR_WELCOME,        "Welcome to the HoverRace Internet Meeting Room"},
        {IDS_IMR_DISCONNECT,     "Disconnecting from the Internet Meeting Room..."},
        {IDS_IMR_ADD_GAME,       "Registering game with the Internet Meeting Room..."},
        {IDS_IMR_DEL_GAME,       "Unregistering game from the Internet Meeting Room..."},
        {IDS_IMR_JOIN_GAME,      "Registering with the Internet Meeting Room..."},
        {IDS_IMR_LEAVE_GAME,     "Unregistering from the Internet Meeting Room..."},
        {IDS_IMR_NOSELECT,       "[no selection]"},
        {IDS_AVAIL,              "Available"},
        {IDS_TRACK_NOTINSTALL,   "Track not installed on your system"},
        {IDS_TRACK_NOTREG,       "You must register to use this track"},
        {IDS_COMM_ERROR,         "Communication error"},
        {IDS_CANT_ADDUSER,       "Unable to add user"},
        {IDS_NOMORE_SHRWR,       "No more Shareware user allowed"},
        {IDS_NOMORE_USER,        "No more user allowed"},
        {IDS_INCOMPAT_VER,       "Incompatible version"},
        {IDS_EXP_KEY,            "Expired key"},
        {IDS_DUAL_USE,           "Already used key  (report for investigation)"},
        {IDS_CANT_REFRESH,       "Unable to send refresh info"},
        {IDS_NOL,                "Not on-line"},
        {IDS_CANT_ADD_CHAT,      "Unable to add chat message"},
        {IDS_CANT_ADD_GAME,      "Unable to add game"},
        {IDS_NOMORE_ENTRY,       "No more entry avail"},
        {IDS_CANT_JOIN,          "Unable to join Game"},
        {IDS_GAME_NA,            "Game no more availlable"},
        {IDS_GAME_FULL,          "Game Full"},
        {IDS_CANT_DEL_GAME,      "Unable to delete Game"},
        {IDS_NOT_OWNER,          "Not owner"},
        {IDS_CANT_LEAVE_GAME,    "Unable to leave game"},
        {IDS_MUST_JOIN,          "Must join first"},
        {IDS_CANT_DEL_USER,      "Unable to delete user"},
        {IDS_CANT_START_GAME,    "Unable to Start Game"},
        {IDS_CANT_ADD_MESSAGE,   "Unable to add message"},
        {IDS_NOT_AUTH,           "Not authorized"},
        {IDS_UNKNOWN_ERROR,      "Unknown error code %d"},
        {IDS_IMR,                "Internet Meeeting Room"},
        {IDS_IMR_PASSVAL,        "Password validation..."},
        {IDS_ENTER_ALIAS,        "You must enter an alias name"},
        {IDS_SELECT_ROOM,        "You must select a room"},
        {IDS_WARN_TO,            "Warning: communication time-out"},
        {IDS_LOC_MSERVER,        "Locating the main server..."},
        {IDS_CANT_FIND_SERVER,   "Unable to find the server\nYou must be connected to the Internet to use this function\nContact Support if the problem persist"},
        {IDS_TO,                 "Communication timeout"},
        {IDS_SERVER_ERROR,       "Server error, please advise the server administrator"},
        {IDS_CANT_CREATE_SOCK,   "Unable to create socket( Contact Support if the problem persist)"},
        {IDS_TCP_SERVER,         "TCP Server"},
        {IDS_CANT_USE_PORT,      "Unable to use the port, try to close some WINSOCK applications"},
        {IDS_PORT_RANGE,         "Port value must be greater than 0"},
        {IDS_CONNECTING_SERV,    "Connecting to server..."},
        {IDS_GET_GAMEINFO,       "Retrieving game info..."},
        {IDS_TCP_CLIENT,         "TCP Client"},
        {IDS_CANT_CONNECT,       "ERROR Unable to connect to server..."},
        {IDS_PLAYER,             "Player"},
        {IDS_LAG,                "Lag.(ms)"},
        {IDS_STATUS,             "Status"},
        {IDS_LOCAL,              "Local"},
        {IDS_CONNECTED,          "Connected"},
        {IDS_REG_BEST_LAP,       "Registering your best lap time to the server"},
        {IDS_DISCONNECTED,       "Disconnected"},
        {IDS_COMPUTING,          "Computing"},
        {IDS_CONNECTING,         "Connecting"},
        {IDS_WAITING_ACK,        "Waiting Ack"},
        {IDS_NO_NET_CONNECT,     "(no network connection)"},
        {IDS_DUAL_REG_KEY,       "An other player is using your registration key"},
        {IDS_F2_TORETURN,        "Press F2 when ready to return to Meeting Room"},
        {IDS_HAS_LEFT,           " has left"},
        {IDS_ALONE_F2,           "You are now alone, press F2"},
        {IDS_ALONE,              "You are now alone"},
        {IDS_TRK_NOTFOUND,       "Track not found"},
        {IDS_BAD_TRK_FORMAT,     "Bad track file format"},
        {IDS_SHOULD_REG,         "You should register to play that track"},
        {IDS_NO_SELECT,          " no selection"},
        {IDS_LAP_RANGE,          "Number of laps should be between 1 and 99"},
        {IDS_RANK_TITLE,         "Rank            Result   Best Lap "},
        {IDS_FLAP_STR,           "%d %-0.10s #%d%*s   --First lap--  %c"},
        {IDS_CHART_FINISH,       "%d %-0.10s #%d%*s %2d.%02d.%02d %2d.%02d.%02d%c"},
        {IDS_CHART,              "%d %-0.10s #%d%*s lap:%-2d   %2d.%02d.%02d%c"},
        {IDS_COUNTDOWN,          "Start in %02d.%02d sec. for %d laps"},
        {IDS_FINISH,             "Finish in %d.%02d.%02d  %d of %d"},
        {IDS_FINISH_SINGLE,      "Finish in %d.%02d.%02d"},
        {IDS_BEST_LAP,           "  Best lap %d.%02d.%02d  "},
        {IDS_HEADER,             "%d.%02d.%02d  Lap:%d/%d"},
        {IDS_LAST_LAP,           "Last lap %d.%02d.%02d  Best %d.%02d.%02d"},
        {IDS_CUR_LAP,            "Current lap %d.%02d.%02d  Best %d.%02d.%02d"},
        {IDS_HIT_TITLE,          "Rank                 For   Agains"},
        {IDS_HIT_CHART,          "%d %-0.10s #%d%*s  %2d      %2d"},
    };

    for (size_t i = 0; i < strs.size(); ++i)
    {
       const auto& item = strs[i];
       std::cout << "Adding ID " << item.first << ": " << item.second << "\n";
       stringTable->insert(item);
    }
}